"""phase 8 ai: query logs

Revision ID: 12b7ca8e4382
Revises: 32151ee056aa
Create Date: 2026-08-21 05:47:28.115446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b7ca8e4382'
down_revision = '32151ee056aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_query_logs',
    sa.Column('query_type', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.String(length=1024), nullable=False),
    sa.Column('observed_facts', sa.String(length=4096), nullable=False),
    sa.Column('inferences', sa.String(length=4096), nullable=False),
    sa.Column('hypotheses', sa.String(length=4096), nullable=False),
    sa.Column('recommendations', sa.String(length=4096), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_query_logs')
    # ### end Alembic commands ###
