"""initial schema

Revision ID: 273f1f1a6fc9
Revises: 
Create Date: 2026-07-29 18:20:34.178368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273f1f1a6fc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.Column('operating_system', sa.String(length=128), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'UNKNOWN', name='assetstatus'), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='assetcriticality'), nullable=False),
    sa.Column('trust_status', sa.Enum('TRUSTED', 'UNKNOWN', 'UNTRUSTED', name='assettruststatus'), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_ip_address'), 'assets', ['ip_address'], unique=False)
    op.create_index(op.f('ix_assets_mac_address'), 'assets', ['mac_address'], unique=False)
    op.create_table('data_quality_warnings',
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_warnings_subject_id'), 'data_quality_warnings', ['subject_id'], unique=False)
    op.create_index(op.f('ix_data_quality_warnings_subject_type'), 'data_quality_warnings', ['subject_type'], unique=False)
    op.create_table('detection_rule_configs',
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='eventseverity'), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('alert_threshold', sa.Integer(), nullable=False),
    sa.Column('suppression_window_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_rule_configs_rule_key'), 'detection_rule_configs', ['rule_key'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.Enum('ADMIN', 'SECURITY_ANALYST', 'NETWORK_ADMINISTRATOR', 'VIEWER', name='rolename'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('worker_heartbeats',
    sa.Column('worker_name', sa.String(length=64), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_heartbeats_worker_name'), 'worker_heartbeats', ['worker_name'], unique=True)
    op.create_table('network_events',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_source', sa.Enum('DISCOVERY', 'MONITORING', 'SYSLOG', 'THREAT_INTEL', 'IDENTITY', 'SIMULATION', 'MANUAL', name='eventsource'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('source_asset_id', sa.String(), nullable=True),
    sa.Column('destination_asset_id', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='eventseverity'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('evidence', sa.String(length=4096), nullable=False),
    sa.Column('event_metadata', sa.String(length=4096), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('parent_event_id', sa.String(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['destination_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['parent_event_id'], ['network_events.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_events_asset_id'), 'network_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_network_events_correlation_id'), 'network_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_network_events_event_source'), 'network_events', ['event_source'], unique=False)
    op.create_index(op.f('ix_network_events_event_type'), 'network_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_network_events_is_synthetic'), 'network_events', ['is_synthetic'], unique=False)
    op.create_index(op.f('ix_network_events_timestamp'), 'network_events', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='eventseverity'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE', 'CLOSED', name='alertstatus'), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('evidence', sa.String(length=4096), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alerts_rule_key'), 'alerts', ['rule_key'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.String(length=1024), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_rule_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_network_events_timestamp'), table_name='network_events')
    op.drop_index(op.f('ix_network_events_is_synthetic'), table_name='network_events')
    op.drop_index(op.f('ix_network_events_event_type'), table_name='network_events')
    op.drop_index(op.f('ix_network_events_event_source'), table_name='network_events')
    op.drop_index(op.f('ix_network_events_correlation_id'), table_name='network_events')
    op.drop_index(op.f('ix_network_events_asset_id'), table_name='network_events')
    op.drop_table('network_events')
    op.drop_index(op.f('ix_worker_heartbeats_worker_name'), table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_table('roles')
    op.drop_index(op.f('ix_detection_rule_configs_rule_key'), table_name='detection_rule_configs')
    op.drop_table('detection_rule_configs')
    op.drop_index(op.f('ix_data_quality_warnings_subject_type'), table_name='data_quality_warnings')
    op.drop_index(op.f('ix_data_quality_warnings_subject_id'), table_name='data_quality_warnings')
    op.drop_table('data_quality_warnings')
    op.drop_index(op.f('ix_assets_mac_address'), table_name='assets')
    op.drop_index(op.f('ix_assets_ip_address'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
