"""phase 7 trace: incidents, links, investigation notes

Revision ID: 32151ee056aa
Revises: 45321204c848
Create Date: 2026-08-18 11:20:53.107584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32151ee056aa'
down_revision = '45321204c848'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('severity', sa.Enum('INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='eventseverity'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(length=2048), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_alerts',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_alerts_alert_id'), 'incident_alerts', ['alert_id'], unique=False)
    op.create_index(op.f('ix_incident_alerts_incident_id'), 'incident_alerts', ['incident_id'], unique=False)
    op.create_table('incident_assets',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_assets_asset_id'), 'incident_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_incident_assets_incident_id'), 'incident_assets', ['incident_id'], unique=False)
    op.create_table('investigation_notes',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('author_user_id', sa.String(), nullable=True),
    sa.Column('author_username', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_notes_incident_id'), 'investigation_notes', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_notes_incident_id'), table_name='investigation_notes')
    op.drop_table('investigation_notes')
    op.drop_index(op.f('ix_incident_assets_incident_id'), table_name='incident_assets')
    op.drop_index(op.f('ix_incident_assets_asset_id'), table_name='incident_assets')
    op.drop_table('incident_assets')
    op.drop_index(op.f('ix_incident_alerts_incident_id'), table_name='incident_alerts')
    op.drop_index(op.f('ix_incident_alerts_alert_id'), table_name='incident_alerts')
    op.drop_table('incident_alerts')
    op.drop_table('incidents')
    # ### end Alembic commands ###
