"""phase 2 discover: assets extended, asset history, scan jobs

Revision ID: 32fb0b02eb5b
Revises: 273f1f1a6fc9
Create Date: 2026-07-30 02:44:05.094638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fb0b02eb5b'
down_revision = '273f1f1a6fc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_history',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.Enum('FIRST_DISCOVERED', 'IP_CHANGED', 'MAC_CHANGED', 'HOSTNAME_CHANGED', 'STATUS_CHANGED', 'RISK_CHANGED', 'METADATA_CHANGED', name='assetchangetype'), nullable=False),
    sa.Column('previous_value', sa.String(length=512), nullable=False),
    sa.Column('new_value', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_history_asset_id'), 'asset_history', ['asset_id'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('initiated_by_user_id', sa.String(), nullable=True),
    sa.Column('target_ranges', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'REFUSED', name='scanstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hosts_discovered', sa.Integer(), nullable=False),
    sa.Column('new_assets', sa.Integer(), nullable=False),
    sa.Column('changed_assets', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_asset_history_asset_id'), table_name='asset_history')
    op.drop_table('asset_history')
    # ### end Alembic commands ###
