"""phase 6 risk: risk scores and factors

Revision ID: 45321204c848
Revises: d439d75198df
Create Date: 2026-08-17 18:12:43.934353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45321204c848'
down_revision = 'd439d75198df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_scores',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_asset_id'), 'risk_scores', ['asset_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_computed_at'), 'risk_scores', ['computed_at'], unique=False)
    op.create_table('risk_factors',
    sa.Column('risk_score_id', sa.String(), nullable=False),
    sa.Column('factor_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_factors_risk_score_id'), 'risk_factors', ['risk_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_factors_risk_score_id'), table_name='risk_factors')
    op.drop_table('risk_factors')
    op.drop_index(op.f('ix_risk_scores_computed_at'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_asset_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    # ### end Alembic commands ###
