"""phase 3 watch: monitoring samples

Revision ID: bd7e3dd59206
Revises: 32fb0b02eb5b
Create Date: 2026-07-30 02:55:58.272688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7e3dd59206'
down_revision = '32fb0b02eb5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_samples',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('metric_type', sa.Enum('AVAILABILITY', 'LATENCY_MS', 'PACKET_LOSS_PCT', name='metrictype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_samples_asset_id'), 'monitoring_samples', ['asset_id'], unique=False)
    op.create_index(op.f('ix_monitoring_samples_metric_type'), 'monitoring_samples', ['metric_type'], unique=False)
    op.create_index(op.f('ix_monitoring_samples_timestamp'), 'monitoring_samples', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_samples_timestamp'), table_name='monitoring_samples')
    op.drop_index(op.f('ix_monitoring_samples_metric_type'), table_name='monitoring_samples')
    op.drop_index(op.f('ix_monitoring_samples_asset_id'), table_name='monitoring_samples')
    op.drop_table('monitoring_samples')
    # ### end Alembic commands ###
