"""phase 4 nexus: asset relationships

Revision ID: d388a8e5c096
Revises: bd7e3dd59206
Create Date: 2026-08-03 20:25:40.949310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd388a8e5c096'
down_revision = 'bd7e3dd59206'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_relationships',
    sa.Column('source_asset_id', sa.String(), nullable=False),
    sa.Column('target_asset_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Enum('CONFIRMED', 'INFERRED', 'UNKNOWN', name='relationshipconfidence'), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('first_observed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_observed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_relationships_relationship_type'), 'asset_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_asset_relationships_source_asset_id'), 'asset_relationships', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_target_asset_id'), 'asset_relationships', ['target_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_relationships_target_asset_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_source_asset_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_relationship_type'), table_name='asset_relationships')
    op.drop_table('asset_relationships')
    # ### end Alembic commands ###
