"""phase 5 detect: network event processed flag

Revision ID: d439d75198df
Revises: d388a8e5c096
Create Date: 2026-08-07 10:22:28.724663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd439d75198df'
down_revision = 'd388a8e5c096'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_events', sa.Column('processed_by_detection', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_network_events_processed_by_detection'), 'network_events', ['processed_by_detection'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_events_processed_by_detection'), table_name='network_events')
    op.drop_column('network_events', 'processed_by_detection')
    # ### end Alembic commands ###
